# Generated by Django 4.0.5 on 2022-06-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Direction Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Direction Slug')),
                ('sort_number', models.PositiveBigIntegerField(verbose_name='Direction Sort Number')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Doctor Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Doctor Slug')),
                ('description', models.TextField(verbose_name='Doctor Description')),
                ('birthday', models.DateField(verbose_name='Doctor Birthday')),
                ('experience', models.PositiveSmallIntegerField(verbose_name='Doctor Experience')),
                ('sort_number', models.DateTimeField(verbose_name='Doctor Sort Number')),
                ('direction', models.ManyToManyField(related_name='Direction', to='core.direction')),
            ],
        ),
    ]
