# Generated by Django 4.0.5 on 2022-06-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='sort_number',
            field=models.PositiveBigIntegerField(verbose_name='Doctor Sort Number'),
        ),
    ]
