# Generated by Django 4.0.5 on 2022-06-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctor_sort_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('sort_number', 'name')},
        ),
    ]
